# Use latest node docker image
image: node:latest

# Cache the downloaded node modules for next time
cache:
  paths:
    - app/node_modules/

# The different stages of our pipeline
stages:
  - test
  - build
  - deploy

# Jobs are defined below
test:
  stage: test
  script: 
    - cd app
    - npm install
    - npm run test
  artifacts:
    paths:
      - app/coverage/

lint:
  stage: test
  script: 
    - cd app
    - npm install
    - npm run lint

build:
  stage: build
  script: 
    - cd app
    - npm install
    - npm run build
  artifacts:
    paths:
      - app/dist/

deploy:
  stage: deploy
  environment:
    name: dev
    url: amazing-mcclintock-998498.netlify.app
    only:
      - dev
    script:
      - cd app
      - npm run build
      - npx netflix-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod

buildLatex:
  image: blang/latex
  script:
    - cd ./doc/assignments
    - latexmk -pdf
  artifacts:
    paths:
      - doc/assignments/*.pdf