# Use latest node docker image
image: node:latest

# Cache the downloaded node modules for next time
cache:
  paths:
    - app/node_modules/

# The different stages of our pipeline
stages:
  - test
  - build

# Jobs are defined below
test:
  stage: test
  script: 
    - cd app
    - apt-get update -y
    - apt-get install xserver-xorg-dev libxi-dev libxext-dev -y
    - npm install
    - npm run test
  artifacts:
    paths:
      - app/coverage/

lint:
  stage: test
  script: 
    - cd app
    - npm install
    - npm run lint

build:
  stage: build
  script: 
    - cd app
    - npm install
    - npm run deploy
  artifacts:
    paths:
      - app/dist/

buildLatex:
  image: blang/latex
  script:
    - cd ./doc/assignments
    - latexmk -pdf
  artifacts:
    paths:
      - doc/assignments/*.pdf