# Use latest node docker image
image: node:latest

# Cache the downloaded node modules for next time
cache:
  paths:
    - app/node_modules/

before-script:
  - cd app

# The different stages of our pipeline
stages:
  - setup
  - test
  - build
  
# Jobs are defined below
setup:
  stage: setup
  script:
  - cd app
  - npm install

test:
  stage: test
  script: npm run test

lint:
  stage: test
  script: npm run lint

build:
  stage: build
  script: npm run build
  artifacts:
    paths:
      - dist/