# Use latest node docker image
image: node:latest

# Cache the downloaded node modules for next time
cache:
  paths:
    - app/node_modules/

# The different stages of our pipeline
stages:
  - test
  - build
  - deploy

# Jobs are defined below
before_script:
  - cd app
  - npm install

test:
  stage: test
  script:
    - npm run test
  artifacts:
    paths:
      - app/coverage/
  coverage: /All\sfiles.*?\|\s+.*?\s+(\d+.\d+)/

lint:
  stage: test
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - app/dist/

deploy:
  stage: deploy
  environment:
    name: dev
    url: covid-model.netlify.app
  only:
    - dev
  script:
    - npm run build
    - npx netflix-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod

buildLatex:
  image: blang/latex
  script:
    - npm run deploy
  artifacts:
    paths:
      - app/dist/