# Use latest node docker image
image: node:latest

# Cache the downloaded node modules for next time
cache:
  paths:
    - app/node_modules/

# The different stages of our pipeline
stages:
  - test
  - build
  - deploy

# Jobs are defined below
before_script:
  - cd app
  - npm ci
  - npm install
  

test:
  stage: test
  script:
    - npm run test
  artifacts:
    paths:
      - app/coverage/
  coverage: /All\sfiles.*?\|.*?\|.*?(\d*\.?\d)/

lint:
  stage: test
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - app/dist/

deploy:
  stage: deploy
  environment:
    name: dev
    url: covid-model.netlify.app
  only:
    - fix-dev-pipeline
  script:
    - npm i -g netlify-cli
    - npm run build
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod