# Use latest node docker image
image: node:latest

# Cache the downloaded node modules for next time
cache:
  untracked: true
  paths:
    - app/node_modules/

# The different stages of our pipeline
stages:
  - setup
  - test
  - build
  - deploy

# Jobs are defined below
setup:
  stage: setup
  script:
    - cd app
    - npm ci
  
test:
  stage: test
  script:
    - cd app
    - npm run test
  artifacts:
    paths:
      - app/coverage/
  coverage: /All\sfiles.*?\|.*?\|.*?(\d*\.?\d)/

lint:
  stage: test
  script:
    - cd app
    - npm run lint

build:
  stage: build
  script:
    - cd app
    - npm run build
  artifacts:
    paths:
      - app/dist/

deploy:
  stage: deploy
  only:
    - dev
  script:
    - cd app
    - npm run build
    - npm i -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod