# Use latest node docker image
image: node:latest

# Cache the downloaded node modules for next time
cache:
  paths:
    - app/node_modules/

# The different stages of our pipeline
stages:
  - test
  - build

# Jobs are defined below
before_script:
  - cd app
  - npm install


test:
  stage: test
  script:
    - npm run test
  artifacts:
    paths:
      - app/coverage/
  coverage: /All\sfiles.*?\|\s+.*?\s+(\d+.\d+)/

lint:
  stage: test
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run deploy
  artifacts:
    paths:
      - app/dist/